### ISSUE TITLE
Export der Wertungen als CSV

### ISSUE THREAD

**Issue by harmoniemand** [opendata-heilbronn/poetryslam#12]

**Comment by BinaryCraX** [comment]
The CSVExportService will export a file with the name of the competition. The file will contain following fields:
- group
- name
- slam
- score1
- score2
- scoreN
- ignoredScore1
- ignoredScore2
- extraScore
- totalScore
- totalScoreWithIgnoredScore
- totalScoreWithIgnoredScoreAndExtraScore
